### ISSUE TITLE
Dealing with Swift exceptions in block

### ISSUE THREAD

**Issue by rsalesas** [mattgallagher/CwlCatchException#1]
Is it possible to modify to support "catching" Swift exceptions ("throws") in the Objective-C handler and passing them onwards?

**Comment by mattgallagher** [comment]
There's no such thing as a Swift exception. If you mean Mach exceptions, then you can catch them with [CwlPreconditionTesting](https://github.com/mattgallagher/CwlPreconditionTesting).

**Comment by rsalesas** [comment]
I mean, if the Swift closure you are wrapping is defined as throwing, then the wrapper doesn't work. Is it possible to handle closures that throw?

**Comment by mattgallagher** [comment]
Catching errors from a `throws` closure is handled by Swift's error handling (`do`/`catch`), not exception handling.

https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html

If you're asking if it's possible to throw a Swift error as an Objective-C exception: not really – they're very different ideas. While you could use Swift's `do`/`catch` to catch a Swift error and create a completely new `NSException` object and raise it, the logic would be specific to your program, not a reusable piece of code.

**Comment by rsalesas** [comment]
Yes, I understand. What I meant was, right now if you use CwlCatchException on a closure that calls functions that throw NSException, they get caught. But if the closure also throws, then it doesn't catch those and rethrow them outside of the closure. It makes writing inside code more difficult as you need a catch inside and a catch outside, and dealing with or returning the error is more difficult. If CwlCatchException caught both ObjC exceptions and thrown Swift errors, it would make the closure a lot cleaner.

**Comment by rsalesas** [comment]
Just an update to confirm this worked. I used a slightly different structure than you did, and added support for crossing the thrown errors. Works really well as this way one outer catch handles everything.

**Comment by mattgallagher** [comment]
A resolution to this problem is available on master.
