### ISSUE TITLE
Xcode 16 Build Warnings

### ISSUE THREAD

**Issue by LowAmmo** [mattgallagher/CwlCatchException#9]
Getting some build warnings when building CwlCatchException - 

     Pods/CwlCatchException/Sources/CwlCatchException/CwlCatchException.swift:52:1: warning: extension declares a conformance of imported type 'NSException' to imported protocol 'Sendable'; this will not behave correctly if the owners of 'Foundation' introduce this conformance in the future
     extension NSException: @unchecked Sendable { }
     ^
     Pods/CwlCatchException/Sources/CwlCatchException/CwlCatchException.swift:52:1: note: add '@retroactive' to silence this warning
     extension NSException: @unchecked Sendable { }
     ^                                 ~~~~~~~~
                                       @retroactive Sendable

I can try to put together a Pull Request to fix this...but might be a few days.

Just trying to eliminate all build warnings - doesn't seem to currently cause any real issues when building with the current Xcode 16 Beta (Beta 5).

**Comment by mattgallagher** [comment]
Merged

**Comment by LowAmmo** [comment]
Thanks, @mattgallagher !
